Abbreviate "Lord Bain";
Abbreviate "something";
Abbreviate "probably ";
Abbreviate "the manor";
Abbreviate "Blackwood";
Abbreviate "Scottish ";
Abbreviate " already ";
Abbreviate " of the ";
Abbreviate "Ysabella";
Abbreviate " in the ";
Abbreviate " through";
Abbreviate " object";
Abbreviate "to the ";
Abbreviate " with ";
Abbreviate " like ";
Abbreviate " your ";
Abbreviate ". The ";
Abbreviate " about";
Abbreviate " this ";
Abbreviate " that ";
Abbreviate ". You ";
Abbreviate "round";
Abbreviate " was ";
Abbreviate "stone";
Abbreviate "ould ";
Abbreviate "blood";
Abbreviate " from";
Abbreviate "have ";
Abbreviate " are ";
Abbreviate " you ";
Abbreviate " and ";
Abbreviate "Rosie";
Abbreviate " the ";
Abbreviate " seem";
Abbreviate " back";
Abbreviate " has ";
Abbreviate "thing";
Abbreviate " but ";
Abbreviate "which";
Abbreviate "here";
Abbreviate "look";
Abbreviate "tion";
Abbreviate "Cora";
Abbreviate " for";
Abbreviate "n't ";
Abbreviate " in ";
Abbreviate " is ";
Abbreviate "nder";
Abbreviate "The ";
Abbreviate "ight";
Abbreviate " to ";
Abbreviate " of ";
Abbreviate "You ";
Abbreviate "ing ";
Abbreviate " you";
Abbreviate "his";
Abbreviate "ed ";
Abbreviate "'s ";
Abbreviate "ear";
Abbreviate "s, ";
Abbreviate "the";
Abbreviate "est";
Abbreviate " a ";
Abbreviate "old";
Abbreviate " in";
Abbreviate "ill";
Abbreviate " co";
Abbreviate ". I";
Abbreviate "ent";
Abbreviate "nce";
Abbreviate ". T";
Abbreviate "hat";
Abbreviate "es ";
Abbreviate "ver";
Abbreviate "all";
Abbreviate "ter";
Abbreviate "ain";
Abbreviate ". A";
Abbreviate "re ";
Abbreviate " be";
Abbreviate "en ";
Abbreviate "and";
Abbreviate "rea";
Abbreviate "not";
Abbreviate "er ";
Abbreviate ".^^";
Abbreviate "an ";
Abbreviate "You";
Abbreviate "now";
Abbreviate "lea";
Abbreviate "ing";
Abbreviate "ly ";
Abbreviate " it";
Abbreviate "ind";
Abbreviate ", ";
Abbreviate ". ";
