Abbreviate ").before()^";
Abbreviate "You can't ";
Abbreviate " Christmas";
Abbreviate " Scottish ";
Abbreviate "Blackwood";
Abbreviate " you can ";
Abbreviate "already ";
Abbreviate " of the ";
Abbreviate " in the ";
Abbreviate " to the ";
Abbreviate " wooden ";
Abbreviate "ed with ";
Abbreviate " small";
Abbreviate "s and ";
Abbreviate " this ";
Abbreviate " been ";
Abbreviate "corner";
Abbreviate " your ";
Abbreviate "rious ";
Abbreviate ". You ";
Abbreviate " with ";
Abbreviate "notice";
Abbreviate ". The ";
Abbreviate "object";
Abbreviate "thing";
Abbreviate "walls";
Abbreviate "manor";
Abbreviate "rough";
Abbreviate " from";
Abbreviate " are ";
Abbreviate " the ";
Abbreviate "which";
Abbreviate " back";
Abbreviate " and ";
Abbreviate "large";
Abbreviate "place";
Abbreviate " lead";
Abbreviate " you ";
Abbreviate "round";
Abbreviate " that";
Abbreviate "north";
Abbreviate " of ";
Abbreviate "You ";
Abbreviate " to ";
Abbreviate " is ";
Abbreviate "ight";
Abbreviate "one ";
Abbreviate "n't ";
Abbreviate "ing ";
Abbreviate "tion";
Abbreviate "The ";
Abbreviate "Cora";
Abbreviate "able";
Abbreviate "nder";
Abbreviate "itch";
Abbreviate "time";
Abbreviate " you";
Abbreviate "room";
Abbreviate "here";
Abbreviate "some";
Abbreviate "_to/";
Abbreviate "have";
Abbreviate " on";
Abbreviate "re ";
Abbreviate "ed ";
Abbreviate " st";
Abbreviate "'s ";
Abbreviate "est";
Abbreviate " co";
Abbreviate "ill";
Abbreviate "see";
Abbreviate "s, ";
Abbreviate " it";
Abbreviate "ine";
Abbreviate "ain";
Abbreviate " a ";
Abbreviate "the";
Abbreviate " be";
Abbreviate ".^^";
Abbreviate "for";
Abbreviate "ear";
Abbreviate "ter";
Abbreviate "rea";
Abbreviate "out";
Abbreviate "ver";
Abbreviate "ly ";
Abbreviate "and";
Abbreviate "ent";
Abbreviate "ing";
Abbreviate ". A";
Abbreviate " in";
Abbreviate ". I";
Abbreviate ", ";
Abbreviate ". ";
Abbreviate "[";
Abbreviate "]";
