Abbreviate "electric torch";
Abbreviate " leads back";
Abbreviate " Christmas";
Abbreviate " something";
Abbreviate " has been ";
Abbreviate " into the ";
Abbreviate " Scottish ";
Abbreviate "centuries";
Abbreviate " you can ";
Abbreviate "Blackwood";
Abbreviate "probably";
Abbreviate " wooden ";
Abbreviate " on the ";
Abbreviate " to the ";
Abbreviate " in the ";
Abbreviate "ed with ";
Abbreviate " of the ";
Abbreviate "portrait";
Abbreviate ". The ";
Abbreviate " your ";
Abbreviate " with ";
Abbreviate "s and ";
Abbreviate " about";
Abbreviate "object";
Abbreviate ". You ";
Abbreviate "have ";
Abbreviate " you ";
Abbreviate "manor";
Abbreviate " and ";
Abbreviate " that";
Abbreviate " from";
Abbreviate " the ";
Abbreviate "which";
Abbreviate " was ";
Abbreviate "Rosie";
Abbreviate "thing";
Abbreviate "ould ";
Abbreviate " seem";
Abbreviate "his ";
Abbreviate "are ";
Abbreviate "The ";
Abbreviate "tion";
Abbreviate "one ";
Abbreviate "here";
Abbreviate " you";
Abbreviate "side";
Abbreviate "ough";
Abbreviate "room";
Abbreviate "n't ";
Abbreviate " is ";
Abbreviate "You ";
Abbreviate "able";
Abbreviate "nder";
Abbreviate "ound";
Abbreviate "ing ";
Abbreviate " in ";
Abbreviate "ight";
Abbreviate " of ";
Abbreviate " to ";
Abbreviate " it ";
Abbreviate "s, ";
Abbreviate ". T";
Abbreviate "ed ";
Abbreviate "now";
Abbreviate " in";
Abbreviate " a ";
Abbreviate "old";
Abbreviate "ate";
Abbreviate "the";
Abbreviate " be";
Abbreviate "ent";
Abbreviate " st";
Abbreviate ".^^";
Abbreviate "ly ";
Abbreviate "rea";
Abbreviate "ain";
Abbreviate "for";
Abbreviate "out";
Abbreviate "cor";
Abbreviate "'s ";
Abbreviate "en ";
Abbreviate ". A";
Abbreviate "est";
Abbreviate "an ";
Abbreviate "not";
Abbreviate "and";
Abbreviate "ver";
Abbreviate ". I";
Abbreviate "ear";
Abbreviate "all";
Abbreviate "ing";
Abbreviate "ter";
Abbreviate ", ";
Abbreviate ". ";
Abbreviate "]";
Abbreviate "[";
